#!/bin/bash
SOLR_DIR="/home/www/solr"
JAVA_OPTIONS="-DSTOP.PORT=8098 -DSTOP.KEY=123 -jar start.jar"
LOG="/var/log/solr.log"
JAVA="/usr/local/java/bin/java"
COMMAND="$JAVA $JAVA_OPTIONS"
case $1 in 
start)
echo "Starting Solr..."
cd $SOLR_DIR
$JAVA $JAVA_OPTIONS 2>>$LOG&
;;

stop)
echo "Stopping Solr..."
cd $SOLR_DIR
$JAVA $JAVA_OPTIONS --stop
;;
 
restart)
echo "Restarting Solr..."
$0 stop
$0 start
;;

*)
echo "Usage : $0 {start|stop|restart}" >&2
exit 1
;;

esac
